Repository shape-up-organization/front-end, pull requests merged in 2023-03, with the labels that each got.

#7 Migrating from Typescript to Javascript
  .env
  .gitignore
  .vscode/extensions.json
  Dockerfile
  README.md
  jsconfig.json
  next.config.js
  package-lock.json
  package.json
  src/contexts/ThemeModeContext.js
  src/contexts/index.js
  src/pages/MyAppProps.d.ts
  src/pages/_app.jsx
  src/pages/_document.jsx
  src/pages/api/hello.ts
  src/pages/index.jsx
  src/styles/createEmotionCache.js
  src/styles/theme.js
  src/styles/useCustomTheme.js
  src/utils/wrappers/ThemeWrapper.jsx
  tsconfig.json
Labels: enhancement

#8 Adding Basic Login Modal
  .eslintrc
  .prettierrc
  .vscode/settings.json
  jsconfig.json
  package-lock.json
  package.json
  src/components/Divider/Divider.jsx
  src/components/Divider/index.js
  src/components/Link/Link.jsx
  src/components/Link/index.js
  src/components/Modal/ExternalButtons.jsx
  src/components/Modal/LoginModal.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/index.js
  src/pages/_app.jsx
  src/pages/index.jsx
  src/styles/globals.css
  src/styles/theme.js
Labels: enhancement

#10 SHAPEUP-46 - Adding Hook Form and ZOD to improve form
  README.md
  package-lock.json
  package.json
  src/components/Modal/modals/LoginModal/LoginModal.jsx
  src/components/Modal/modals/LoginModal/index.js
  src/components/Modal/modals/SignupModal.jsx
  src/components/Modal/modals/SignupModal/SignupModal.jsx
  src/components/Modal/modals/SignupModal/index.js
  src/components/Modal/modals/SignupModal/schema.js
  src/styles/useCustomTheme.js
  src/utils/wrappers/ThemeWrapper.jsx
Labels: documentation, enhancement

#11 Integrating with Back-end on Sign Up
  .env
  jsconfig.json
  package-lock.json
  package.json
  src/api/users/create.js
  src/api/users/index.js
  src/components/Link/index.js
  src/components/LinkButton/LinkButton.jsx
  src/components/LinkButton/index.js
  src/components/Modal/modals/LoginModal/LoginModal.jsx
  src/components/Modal/modals/SignupModal/SignupModal.jsx
  src/components/Modal/modals/SignupModal/schema.js
  src/components/TextField/TextField.jsx
  src/components/TextField/index.js
  src/contexts/ThemeModeContext.js
  src/contexts/ThemeModeProvider.jsx
  src/contexts/index.js
  src/pages/_app.jsx
  src/utils/wrappers/ThemeWrapper.jsx
Labels: enhancement

#12 Modals to Landing Page
  .env
  .eslintrc
  .prettierrc
  .vscode/settings.json
  README.md
  jsconfig.json
  package-lock.json
  package.json
  src/api/users/create.js
  src/api/users/index.js
  src/components/Divider/Divider.jsx
  src/components/Divider/index.js
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
  src/components/LandingPage/LandingPage.jsx
  src/components/LinkButton/LinkButton.jsx
  src/components/LinkButton/index.js
  src/components/Modal/Modal.jsx
  src/components/Modal/components/ExternalButtons.jsx
  src/components/Modal/index.js
  src/components/Modal/modals/LoginModal/LoginModal.jsx
  src/components/Modal/modals/LoginModal/index.js
  src/components/Modal/modals/SignupModal/SignupModal.jsx
  src/components/Modal/modals/SignupModal/index.js
  src/components/Modal/modals/SignupModal/schema.js
  src/components/TextButton/TextButton.jsx
  src/components/TextButton/index.js
  src/components/TextField/TextField.jsx
  src/components/TextField/index.js
  src/contexts/ThemeModeContext.js
  src/contexts/ThemeModeProvider.jsx
  src/contexts/index.js
  src/pages/_app.jsx
  src/pages/_document.jsx
  src/pages/index.jsx
  src/styles/globals.css
  src/styles/theme.js
  src/styles/useCustomTheme.js
  src/utils/wrappers/ThemeWrapper.jsx
Labels: enhancement

#13 Landing Page
  .env
  .eslintrc
  .prettierrc
  .vscode/settings.json
  README.md
  jsconfig.json
  package-lock.json
  package.json
  public/Group 198 (1).jpg
  public/Group 198.jpg
  public/corrida.jfif
  public/exercicio.jpg
  src/api/users/create.js
  src/api/users/index.js
  src/components/Banner/Banner.jsx
  src/components/Banner/index.js
  src/components/Divider/Divider.jsx
  src/components/Divider/index.js
  src/components/Footer/Footer.jsx
  src/components/Footer/index.js
  src/components/Header/Header.jsx
  src/components/Header/index.js
  src/components/LandingPage/LandingPage.jsx
  src/components/LandingPage/index.js
  src/components/LinkButton/LinkButton.jsx
  src/components/LinkButton/index.js
  src/components/Modal/Modal.jsx
  src/components/Modal/components/ExternalButtons.jsx
  src/components/Modal/index.js
  src/components/Modal/modals/LoginModal/LoginModal.jsx
  src/components/Modal/modals/LoginModal/index.js
  src/components/Modal/modals/SignupModal/SignupModal.jsx
  src/components/Modal/modals/SignupModal/index.js
  src/components/Modal/modals/SignupModal/schema.js
  src/components/Photo/Photo.jsx
  src/components/Photo/index.js
  src/components/TextButton/TextButton.jsx
  src/components/TextButton/index.js
  src/components/TextField/TextField.jsx
  src/components/TextField/index.js
  src/contexts/ThemeModeContext.js
  src/contexts/ThemeModeProvider.jsx
  src/contexts/index.js
  src/pages/_app.jsx
  src/pages/_document.jsx
  src/pages/index.jsx
  src/styles/globals.css
  src/styles/theme.js
  src/styles/useCustomTheme.js
  src/utils/wrappers/ThemeWrapper.jsx
Labels: documentation, enhancement

#14 Datepicker error colors
  src/components/Modal/modals/SignupModal/SignupModal.jsx
Labels: bug

#16 Basic Routing with JWT Auth
  .eslintrc
  .husky/pre-commit
  .vscode/settings.json
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/api/users/create.js
  src/api/users/index.js
  src/assets/images/page-not-found-en.png
  src/assets/images/page-not-found-pt.png
  src/components/Banner/Banner.jsx
  src/components/ErrorPage/ErrorPage.jsx
  src/components/ErrorPage/index.js
  src/components/Footer/Footer.jsx
  src/components/LandingPage/LandingPage.jsx
  src/components/LinkButton/LinkButton.jsx
  src/components/LoadingPage/LoadingPage.jsx
  src/components/LoadingPage/index.js
  src/components/LoggedPage/LoggedPage.jsx
  src/components/LoggedPage/index.js
  src/components/Modal/modals/LoginModal/LoginModal.jsx
  src/components/Modal/modals/LoginModal/schema.js
  src/components/Modal/modals/SignupModal/SignupModal.jsx
  src/components/Modal/modals/SignupModal/SignupModal.test.jsx
  src/components/Modal/modals/SignupModal/schema.js
  src/components/Photo/Photo.jsx
  src/components/ProtectedLayout/ProtectedLayout.jsx
  src/components/ProtectedLayout/index.js
  src/contexts/AuthProvider.jsx
  src/contexts/RoutesProvider.jsx
  src/contexts/SnackbarProvider.jsx
  src/contexts/index.js
  src/main.jsx
  src/styles/theme.js
Labels: enhancement

#20 Fixing Vercel routes
  vercel.json
Labels: bug, enhancement

#21 Improving signup modal validations with zod
  src/components/Modal/modals/SignupModal/SignupModal.test.jsx
  src/components/Modal/modals/SignupModal/schema.js
  src/contexts/RoutesProvider.jsx
Labels: enhancement

#23 Implementing atomic design
  .eslintrc
  .gitignore
  jsconfig.json
  src/components/Modal/index.js
  src/components/atoms/Divider/Divider.jsx
  src/components/atoms/Divider/index.js
  src/components/atoms/ExternalButtons/ExternalButtons.jsx
  src/components/atoms/ExternalButtons/index.js
  src/components/atoms/LinkButton/LinkButton.jsx
  src/components/atoms/LinkButton/index.js
  src/components/atoms/Photo/Photo.jsx
  src/components/atoms/Photo/index.js
  src/components/atoms/TextButton/TextButton.jsx
  src/components/atoms/TextButton/index.js
  src/components/atoms/TextField/TextField.jsx
  src/components/atoms/TextField/index.js
  src/components/molecules/Modals/LoginModal/LoginModal.jsx
  src/components/molecules/Modals/LoginModal/index.js
  src/components/molecules/Modals/LoginModal/schema.js
  src/components/molecules/Modals/SignupModal/SignupModal.jsx
  src/components/molecules/Modals/SignupModal/SignupModal.test.jsx
  src/components/molecules/Modals/SignupModal/index.js
  src/components/molecules/Modals/SignupModal/schema.js
  src/components/organisms/Banner/Banner.jsx
  src/components/organisms/Banner/index.js
  src/components/organisms/Footer/Footer.jsx
  src/components/organisms/Footer/index.js
  src/components/organisms/Header/Header.jsx
  src/components/organisms/Header/index.js
  src/components/pages/ErrorPage/ErrorPage.jsx
  src/components/pages/ErrorPage/index.js
  src/components/pages/LandingPage/LandingPage.jsx
  src/components/pages/LandingPage/index.js
  src/components/pages/LoadingPage/LoadingPage.jsx
  src/components/pages/LoadingPage/index.js
  src/components/pages/LoggedPage/LoggedPage.jsx
  src/components/pages/LoggedPage/index.js
  src/components/templates/Modal/Modal.jsx
  src/components/templates/Modal/index.js
  src/components/templates/ProtectedLayout/ProtectedLayout.jsx
  src/components/templates/ProtectedLayout/index.js
  src/contexts/RoutesProvider.jsx
  vite.config.js
Labels: enhancement

#22 Adding input masks
  package-lock.json
  package.json
  src/api/users/index.js
  src/components/atoms/TextField/TextField.jsx
  src/components/molecules/LoginModal/LoginModal.jsx
  src/components/molecules/LoginModal/index.js
  src/components/molecules/LoginModal/schema.js
  src/components/molecules/SignupModal/SignupModal.jsx
  src/components/molecules/SignupModal/SignupModal.test.jsx
  src/components/molecules/SignupModal/index.js
  src/components/molecules/SignupModal/schema.js
  src/components/pages/LandingPage/LandingPage.jsx
  src/components/templates/Modal/Modal.jsx
  src/components/templates/Modal/index.js
  src/utils/masks.js
Labels: enhancement

#24 Applying responsiveness
  package-lock.json
  package.json
  src/assets/images/dog.png
  src/components/molecules/LoginModal/LoginModal.jsx
  src/components/molecules/Modals/LoginModal/LoginModal.jsx
  src/components/molecules/Modals/LoginModal/index.js
  src/components/molecules/Modals/LoginModal/schema.js
  src/components/molecules/Modals/SignupModal/SignupModal.jsx
  src/components/molecules/Modals/SignupModal/SignupModal.test.jsx
  src/components/molecules/Modals/SignupModal/index.js
  src/components/molecules/Modals/SignupModal/schema.js
  src/components/molecules/SignupModal/SignupModal.jsx
  src/components/organisms/Banner/Banner.jsx
  src/components/organisms/Banner/Banner.styles.js
  src/components/organisms/Footer/Footer.jsx
  src/components/organisms/Header/Header.jsx
  src/components/organisms/Header/Header.styles.js
  src/components/pages/LandingPage/LandingPage.jsx
  src/components/templates/Modal/Modal.jsx
  src/components/templates/Modal/Modal.styles.js
Labels: enhancement

#25 Multi-language Support with i18next and Migrating from @mui/styles
  .gitignore
  package-lock.json
  package.json
  public/locales/en-US/translation.json
  public/locales/pt-BR/translation.json
  public/vite.svg
  src/components/organisms/Banner/Banner.jsx
  src/components/organisms/Banner/Banner.styles.js
  src/components/organisms/Header/Header.jsx
  src/components/organisms/Header/Header.styles.js
  src/components/templates/Modal/Modal.jsx
  src/components/templates/Modal/Modal.styles.js
  src/i18n.js
  src/main.jsx
Labels: hot, build, enhancement, bug

#26 Testing basic components
  src/components/atoms/LinkButton/LinkButton.test.jsx
  src/components/atoms/Photo/Photo.test.jsx
  src/components/atoms/TextButton/TextButton.test.jsx
  src/components/molecules/Modals/LoginModal/LoginModal.test.jsx
Labels: test
